### ISSUE TITLE
Confusion about Security Group definition in module-2 CloudFormation Script

### ISSUE THREAD

**Issue by rttomlinson** [aws-samples/aws-modern-application-workshop#10]
[https://github.com/aws-samples/aws-modern-application-workshop/blob/master/module-2/cfn/core.yml](https://github.com/aws-samples/aws-modern-application-workshop/blob/master/module-2/cfn/core.yml)

I am confused by Lines 194-209. I am under the impression that internet-facing load balancers needs at minimum to be associated with a subnet that has a IGW. The application and classic load balancers can have a security group associated with them but not a Network Load Balancer. The security group defined in this section (Lines 194-209) is allowing **all** traffic into the Fargate container instances hosted in ECS, which doesn't really seem to be the intention of the security group. 

My proposed solution is to limit the ingress policy of the security group to only that of the VPC range. Because the instances are in a private subnet, the security group is redundant, but some amount of redundancy is good. In the event that someone was able to change the subnet where the containers instances live to a public one, or move the instances into a public subnet, the security group limiting incoming traffic to only from within the VPC would still prevent outside traffic from accessing the resources originally in the private subnet.

**Comment by abaird986** [comment]
Good suggestion, updated the core.yml file to reflect this as part of e37559e08303cc3655fa69b6550624a7674b32f5.
