### ISSUE TITLE
Repo does not match AWS live tutorial doc

### ISSUE THREAD

**Issue by thedon-chris** [aws-samples/aws-modern-application-workshop#104]
The Github repo does not match the AWS production tutorial site.

A specific example is Python Module 1, Step B (Update the S3 Bucket Policy).

AWS Documentation does not mention Cloudfront step, Github documentation does.

**Comment by wksantiago** [comment]
indeed

**Comment by abaird986** [comment]
We are aware of this and there aren't any plans to keep both venues in-sync. The website version of the tutorial isn't meant to be the "production" or "live" version of the tutorial, but rather just another publication of the tutorial where our customers may discover it.
