### ISSUE TITLE
deploy-frontend.sh does not work on .NET module1

### ISSUE THREAD

**Issue by whuhschool** [aws-samples/aws-modern-application-workshop#106]
You will want to add 

> npm install --save-dev @angular-devkit/build-angular

in the frontend folder before running the script.

**Comment by abaird986** [comment]
@kneekey23 and @allenmichael - can you take a look at this one and see if a PR is needed?

**Comment by allenmichael** [comment]
@abaird986 I'm working on updating the version of Angular that the .NET module uses and I'll include this fix with that PR.

**Comment by abaird986** [comment]
This was pushed. Closing.
