### ISSUE TITLE
Getting token claims in the web api?

### ISSUE THREAD

**Issue by LUS1N** [aws-samples/aws-modern-application-workshop#108]
Hi, 

nice workshop.

I have a question though, how would I go about getting the claims from the cognito user pools authorizer in this application? say I want to do some claims-based authorization, would I need to decode the JWT auth token in the webapi or is there a way to access the authorizer output?

**Comment by abaird986** [comment]
Thanks for the question and appreciate that you've enjoyed the workshop.

Those details for decoding the jwt are here: https://aws.amazon.com/premiumsupport/knowledge-center/decode-verify-cognito-json-token/
