### ISSUE TITLE
Load balancer does not respond: timeout

### ISSUE THREAD

**Issue by ArtemKushnerov** [aws-samples/aws-modern-application-workshop#114]
Hi. I'm facing similar issue as #14 , load balancer is not connecting  - request expires with a timeout. I tried suggestions from there: seems like I got it right with subnets, and also I checked a running task in a cluster via aws console, it shows a bunch of 200 health check responses, but not mysfits responses. How can I investigate further? Is there a way to see some logs on load balancer itself?

**Comment by abaird986** [comment]
Hi @ArtemKushnerov - sorry you're having this issue.  When we've seen the symptoms you're describing in the past, it has almost always been due to at least one of the subnets being misused when creating the NLB and/or ECS service.  

Can you confirm that the CloudFormation describe-stacks output that includes your subnetIds shows both public subnetIds as matching the ones used for the NLB and both private subnetIds as the ones matching the ECS service?

**Comment by ArtemKushnerov** [comment]
Hi @abaird986! I was writing response to you with all my configs and all of a sudden it started working. This is weird though. Thanks!

**Comment by danfs** [comment]
I'm having a similar issue, have checked the subnetIds, does it just take some time to initialize?

**Comment by abaird986** [comment]
Hi @danfs  - another common problem that can result in an unresponsive service is if the IAM roles for the ECS service and ECS task are flipped.  You can also check the ECS service console and see if any service/task logs are being reported that would indicate an error occurring when trying to provision the tasks.

**Comment by danfs** [comment]
Thanks @abaird986 for your quick response! I had a look at the IAM roles and they looked okay, but then saw [this](https://github.com/aws-samples/aws-modern-application-workshop/issues/14#issuecomment-561933041) and had a dig around on the console and noticed the task wasn't running, and when I tried to run it it popped up with: 

> The default capacity provider strategy for the specified cluster does not contain a capacity provider. Update the default capacity provider strategy to associate one or more capacity providers and try again.

**Comment by sreejithkadavil** [comment]
Hi, I am doing the tutorial and in module 2 I am stuck with the Step 4, where I have to test the service. The NLB doesnt respond. 
<img width="728" alt="Captureforawsissue1" src="https://user-images.githubusercontent.com/46398729/88168531-3228f000-cc38-11ea-9194-81f082c47e47.PNG">
