### ISSUE TITLE
Module 2 Testing the Service Locally requires user credentials

### ISSUE THREAD

**Issue by dbw12345** [aws-samples/aws-modern-application-workshop#116]
I have successfully built the docker image and obtained the tag. However, I am unable to preview the application in the Cloud9 IDE browser. I have tried multiple requests and get different responses:

1) docker run -p 8080:8080 MY_ID.dkr.ecr.us-west-2.amazonaws.com/mythicalmysfits/service:latest returns "Cannot GET..." response. MY_ID is my account id from cloud formation output.
2) docker run -p 8080:8080 MY_ID.dkr.ecr.us-west-2.amazonaws.com/mysfits returns "Cannot GET..." response.
3) https://MY_ID.dkr.ecr.us-west-2.amazonaws.com/mysfits returns a request to re-enter user credentials. However, the correct user credentials are not accepted.

**Comment by abaird986** [comment]
Hi @dbw12345  - apologies for the delay on responding here. The error message you're getting from Docker would indicate that it doesn't recognize that ecr string as the image tag.  This could be a sign that something went wrong when either building or tagging the image.  Try and perform those steps again before running the container.
