### ISSUE TITLE
MythicalMysfitsServiceCodeBuildProject  failes with an error

### ISSUE THREAD

**Issue by vcloudguy** [aws-samples/aws-modern-application-workshop#122]
BUILD | Failed | COMMAND_EXECUTION_ERROR: Error while executing command: docker tag mythicalmysfits/service:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mythicalmysfits/service:latest. Reason: exit status 1

POST_BUILD | Failed | COMMAND_EXECUTION_ERROR: Error while executing command: docker push 
$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mythicalmysfits/service:latest. Reason: exit status 1

UPLOAD_ARTIFACTS | Failed | CLIENT_ERROR: no matching artifact paths found

Any ideas why am I getting this error?

**Comment by abaird986** [comment]
There are some changes that are required in the json file to create the CodeBuild Project:
https://github.com/aws-samples/aws-modern-application-workshop/blob/python/module-2/aws-cli/code-build-project.json

These errors could be a sign that those commands are looking for the AccountId and Region variables to be appropriately set but still have the placeholder values instead.

**Comment by abaird986** [comment]
Closing after inactivity. Please comment/reopen if the issue persists.

**Comment by mossibat** [comment]
@abaird986 the error happens in module-4 after this push: git commit -m "Update service code backend to enable additional website features."

**Comment by postpersonality** [comment]
I've got the same error. The reason was 
```
docker pull toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

https://github.com/aws-samples/aws-modern-application-workshop/issues/237
