### ISSUE TITLE
Web URLs do not contain "website" in Module 1

### ISSUE THREAD

**Issue by banglabs-eu** [aws-samples/aws-modern-application-workshop#151]
Working in eu-west-1, the link 

`http://REPLACE_ME_BUCKET_NAME.s3-website-REPLACE_ME_YOUR_REGION.amazonaws.com`
is not correct. It should be 

`http://REPLACE_ME_BUCKET_NAME.s3-REPLACE_ME_YOUR_REGION.amazonaws.com`

**Comment by abaird986** [comment]
Hi @SeamlessIO  - the list of endpoints come from this page in our docs: https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_website_region_endpoints.  Using the -website or .website domain name refers to the static website-relevant behaviors that S3 can enable.
