### ISSUE TITLE
python-cdk: MythicalMysfitsPipeline deployment fails with "Invalid action configuration"

### ISSUE THREAD

**Issue by trivikr** [aws-samples/aws-modern-application-workshop#153]
Steps followed: https://github.com/aws-samples/aws-modern-application-workshop/blob/8aadd1ac77af2f101a84fe6f42bb7ecfbebb755b/module-2/README.md

The deployment in MythicalMysfitsPipeline fails with "Invalid action configuration" "The AWS ECS container web does not exist"
![Invalid action configuration](https://user-images.githubusercontent.com/16024985/69911249-8e9b7e80-13cd-11ea-836e-d94173759224.png)

Confirmed that:
* CodePipeline build is successful, and docker image is updated
* The image digest in Amazon ECS Cluster Service Task is not updated

**Comment by trivikr** [comment]
I forced ecs update-service by running following command:
```console
aws ecs update-service --cluster <cluster name> --service <service name> --force-new-deployment
```

StackOverflow answer: https://stackoverflow.com/a/48572274

**Comment by dstroppa** [comment]
Thanks for reporting this @trivikr, this has been fixed now. The problem was that we had the wrong container name in the buildspec file and that didn't match the one in the task definition.
