### ISSUE TITLE
My s3 site is blank

### ISSUE THREAD

**Issue by jschwarzwalder** [aws-samples/aws-modern-application-workshop#18]
[My site](http://mythical-mysfits-bucket-name-py.s3-website-eu-west-1.amazonaws.com/) is not showing creatures. 

![image](https://user-images.githubusercontent.com/8946787/43362569-6cde23fe-92a2-11e8-8c8e-6ce72ba226f3.png)

I completed module 3, and I still cannot see creatures. on my machine. 

Am I doing something wrong?

I can load https://www.mythicalmysfits.com/

**Comment by abaird986** [comment]
Hi @jschwarzwalder is this problem still going on?  Can you view the Web Console (looks like you're using Firefox, it's under Tools -> Web Developer -> Web Console) to see what errors are being reported by your page? You should be able to look at the Console tab to see logged errors and the Network tab to see the requests/responses being sent to the backend service.

**Comment by jschwarzwalder** [comment]
I was able to fix it, and created a pull request to update the instructions where I was confused. 

I will close this issue now. 

Thank you for your response.
