### ISSUE TITLE
module-2 : Docker build does not work with latest ubuntu image

### ISSUE THREAD

**Issue by NicolaAtorino** [aws-samples/aws-modern-application-workshop#198]
When running for the first time the command 'docker build . ' the operation will fail because the system cannot find the package python-pip . 

Modifying the dockerfile first line this way fixes the issue :

from 

`FROM ubuntu:latest`

to 

`FROM ubuntu:18.04`

i am not a linux expert so no idea what changed between the 18.04 and the latest version, but wanted to signal the issue because it can be quite frustrating as few information can be found on the internet

**Comment by midapsh** [comment]
Given you are using Python, you should try #192 response =)

**Comment by midapsh** [comment]
And I'm pretty sure the following will happen to you too #199

**Comment by midapsh** [comment]
Besides, Ubuntu20.04 doesn't have Python2 by default
https://wiki.ubuntu.com/FocalFossa/ReleaseNotes?_ga=2.28324668.1238828124.1589170199-493331598.1589170199

**Comment by ebalakumar** [comment]
Ubuntu latest is not shipping python2.7. Rather than changing the base image we can use python3-pip etc. This works. I have raised a PR regarding the same. 

https://github.com/aws-samples/aws-modern-application-workshop/pull/201

**Comment by JoeFromSJersey** [comment]
> When running for the first time the command 'docker build . ' the operation will fail because the system cannot find the package python-pip .
> 
> Modifying the dockerfile first line this way fixes the issue :
> 
> from
> 
> `FROM ubuntu:latest`
> 
> to
> 
> `FROM ubuntu:18.04`
> 
> i am not a linux expert so no idea what changed between the 18.04 and the latest version, but wanted to signal the issue because it can be quite frustrating as few information can be found on the internet

Thanks for pointing this out man, it was definitely driving me nuts for a bit.
