### ISSUE TITLE
What is  VPC Link

### ISSUE THREAD

**Issue by jschwarzwalder** [aws-samples/aws-modern-application-workshop#21]
In module 4, I need to provide an VPC ID for the VPC link,  "connectionId": "REPLACE_ME_VPC_LINK_ID"

I have a VPCID from the LoadBalancers, TargetGroups, and the MythicalMysfitsCoreStack:VPCId

Which one should I use?

**Comment by abaird986** [comment]
Hi @jschwarzwalder !

It's actually a separate resource that the instructions have you copy in the previous step:

Create the VPC Link for our upcoming REST API using the following CLI command (you will need to replace the indicated value with the ARN you saved when the NLB was created in module 2):

```
aws apigateway create-vpc-link --name MysfitsApiVpcLink --target-arns REPLACE_ME_NLB_ARN
```
The response to the above will indicate that a new VPC link is being provisioned and is in PENDING state. Copy the indicated id for future use when we create our REST API in the next step.
```
{
    "status": "PENDING",
    "targetArns": [
        "YOUR_ARN_HERE"
    ],
    "id": "abcdef1",
    "name": "MysfitsApiVpcLink"
}
```
If you don't have access to that response anymore, you can run this CLI command to get the ID:

```
aws apigateway get-vpc-links
```

https://docs.aws.amazon.com/cli/latest/reference/apigateway/get-vpc-links.html
