### ISSUE TITLE
Module 3 batch-write-item Issue

### ISSUE THREAD

**Issue by Ken501** [aws-samples/aws-modern-application-workshop#255]
Currently trying to add the populate-dynamodb.json to the table I created in DynamoDB. For context I am running this project locally on my machine from studio code.  I am using the following command: 

Input: 

aws dynamodb batch-write-item --region us-east-1 --request-items file://b:/'cloned repos'/module-3/aws-cli/populate-dynamodb.json

Output:  

Error parsing parameter '--request-items': Unable to load paramfile (b:/cloned repos/module-3/aws-cli/populate-dynamodb.json), 
text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix. 

When I apply the recommended fix above and run the CLI again I get the following: 

Input: 

aws dynamodb batch-write-item --region us-east-1 --request-items fileb://b:/'cloned repos'/module-3/aws-cli/populate-dynamodb.json

Output: 

'in <string>' requires string as left operand, not int

I have not done any changes to the populate-dynamodb.json

**Comment by cesammaz** [comment]
from within the "cdk" root folder, I did:

aws dynamodb batch-write-item --request-items file://../source/module-3/data/populate-dynamodb.json

you have an issue with your relative path.
