### ISSUE TITLE
mythicalmysfits.com needs to redirect to www

### ISSUE THREAD

**Issue by miketheman** [aws-samples/aws-modern-application-workshop#3]
In order to encourage visiting the site when exploring the workshop, allow a user to type in the URL and redirect them to the subdomain.

**Comment by miketheman** [comment]
The URL described features in the page you provided as well as in  the project's readme:

<img width="889" alt="screenshot 2018-07-18 14 32 11" src="https://user-images.githubusercontent.com/529516/42900640-60f78228-8a97-11e8-838b-cc5dda23c354.png">

When a user, reading this off a projected screen, such as in a workshop setting, they are likely to type in `mythicalmysfits.com` and go nowhere. Adding a Route53 ALIAS record or other mechanism to send someone to the www. subdomain will help.

**Comment by abaird986** [comment]
Updated, good callout, thanks!
