### ISSUE TITLE
Doesn't include correct resources for updating policy in Module 1

### ISSUE THREAD

**Issue by taylars** [aws-samples/aws-modern-application-workshop#37]
The steps outlined in the module calls for the following to be executed in the CLI:

aws s3api put-bucket-policy --bucket bucket-name --policy file://~/environment/aws-modern-application-workshop/module-1/aws-cli/website-bucket-policy.json

However, "website-bucket-policy.json" is not included in the workshop materials.

**Comment by Doug-AWS** [comment]
We are re-architecting the workshop to support various languages. Switch to the python branch (git checkout python from the command line) and you'll find website-bucket-policy.json in module-1/aws-cli.

**Comment by taylars** [comment]
Sounds good, thanks!

**Comment by doomtoo** [comment]
It's still an Issue- can someone update the tutorial with the working information? 

Going through tutorials to learn a system, and them being outdated/ not working isn't a great experience.

**Comment by kneekey23** [comment]
Totally agree and we are working on updating them to have accurate info and provide support for various languages. Have you switched to the language branch you are doing the tutorial in and still not been able to find it in module-1/aws-cli?

**Comment by kneekey23** [comment]
@doomtoo have you replaced any values in that json file that could be causing it to error? Try dumping it into a json validator just to make sure. and yes it's a lot easier! the scripts do most of the work for you, no replacing values.

**Comment by doomtoo** [comment]
@kneekey23 Lol, yeah, I just saw I didn't replace the bucket name in the JSON file, but it's still throwing the same issue saying it's invalid JSON. I did throw it in a JSON validator, and it shows valid JSON, so not sure why it doesn't see the file as valid JSON. Even creating a new file with "{}" in throws the same error. 

Even grabbing sample JSON policies (https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-policy.html) and replacing them with my bucket name throws the same error: 

"An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Policies must be valid JSON and the first byte must be '{'"

So I'll switch to the dotnet branch(or even set the policy using the s3 interface), since something is going wrong. Thanks for the advice!

**Comment by Doug-AWS** [comment]
You must use the file:// prefix. I just confirmed it works on my Windows laptop, where website-bucket-policy.json is in the current folder and BUCKET is set in the json file:

aws s3api put-bucket-policy --bucket BUCKET --policy file://website-bucket-policy.json

Don't forget you need to update BUCKET in the json file:

{
   "Statement": [
      {
         "Effect": "Allow",
         "Principal": "*",
         "Action": "s3:GetObject",
         "Resource": "arn:aws:s3:::BUCKET/*"
      }       
   ]
}

**Comment by abaird986** [comment]
Hi @doomtoo, based on the command posted, it looks like you're following the tutorial on the Developer Center website (https://aws.amazon.com/getting-started/projects/build-modern-app-fargate-lambda-dynamodb-python/module-one/).  

The instructions in the README of this repository on the Python branch are up-to-date and what you should follow:
https://github.com/aws-samples/aws-modern-application-workshop/tree/python

That Developer Center set of instructions is going to be out of date for some time still.  I'll see if we can have that site updated to indicate it clearly that it's out of date.

**Comment by FeelingMathy** [comment]
Hi from 2021, this is still broken. Please fix.

**Comment by FeelingMathy** [comment]
> Hi @doomtoo, based on the command posted, it looks like you're following the tutorial on the Developer Center website (https://aws.amazon.com/getting-started/projects/build-modern-app-fargate-lambda-dynamodb-python/module-one/).
> 
> The instructions in the README of this repository on the Python branch are up-to-date and what you should follow:
> https://github.com/aws-samples/aws-modern-application-workshop/tree/python
> 
> That Developer Center set of instructions is going to be out of date for some time still. I'll see if we can have that site updated to indicate it clearly that it's out of date.

Hi abaird986, I followed the instructions at that link, they appear identical to what amazon has hosted. They also don't work. I still get **"An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Policy has invalid resource"**

JSON changes: 

`{
  "Id": "MyPolicy",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "PublicReadForGetBucketObjects",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::lordofthebuckets/*"
    }
  ]
}`

CLI call: 
`ec2-user:~/environment/aws-modern-application-workshop (python) $ aws s3api put-bucket-policy --bucket lordofthebuckets --policy file://~/environment/aws-modern-application-workshop/module-1/aws-cli/website-bucket-policy.json
`

the path seems correct, I have the correct spelling, screenshots match, etc. just a heads up.
