### ISSUE TITLE
module1 folder is missing

### ISSUE THREAD

**Issue by abiodunajibike** [aws-samples/aws-modern-application-workshop#38]
module1 folder is missing from the master branch. This makes it difficult to continue with the tutorial in Module1 (Create static website) Step3 )Host the website on S3) as the bucket policy is missing.

I had to checkout the python branch before i could see the bucket policy in module-1/aws-cli/website-bucket-policy.json.

**Comment by phrankson** [comment]
> module1 folder is missing from the master branch. This makes it difficult to continue with the tutorial in Module1 (Create static website) Step3 )Host the website on S3) as the bucket policy is missing.
> 
> I had to checkout the python branch before i could see the bucket policy in module-1/aws-cli/website-bucket-policy.json.

Hello Abiodun, please can you help me out as well, I am new to this, how did you go about the python branch

**Comment by abiodunajibike** [comment]
@phrankson You just need to git checkout the python branch, there are other branches such as go, java etc. I chose python for no reason other than the fact that it contains the missing folder.

`ec2-user:~/environment/aws-modern-application-workshop (master) $ git checkout python`

**Comment by phrankson** [comment]
Thanks, helped a lot

**Comment by abaird986** [comment]
Hey @phrankson  and @abiodunajibike, appreciate you raising this issue and getting involved here on the workshop!  

The master branch only contains a README file with the instructions to proceed into the language specific workshops.  From the bottom of the master branch README:

> Choose Your Language

> This workshop is offered in different programming languages so that you can choose the workshop experience most relevant to you! Please follow one of the below links to begin the workshop in the language of your choosing:

>    Python
>   .NET
>   More coming soon!

When you follow the link to either the Python or .NET branch of the repository, there are full module-based instructions there, including an initial step about cloning the language specific branch.

Can you give me some details about what led to cloning the master branch based on the above instructions?  We'd like to make it more clear for future developers following the tutorial.

Is there a chance that you followed the bottom link to the [AWS Developer Center](https://aws.amazon.com/developer/)  and followed the instructions there? If so, we are aware that the instructions there have become out of date with the GitHub repository instructions where we now have separate branches for each language supported.

Again, sorry about the confusion here and hope you were able to move past it and through the rest of the workshop!

**Comment by abiodunajibike** [comment]
Hello @abaird986,

Yes, i stumbled on the workshop through the [AWS Developer Center](https://aws.amazon.com/developer/). And like you rightly pointed out, it didn't have any instructions to choose a language. 

I only decided to check out the content of the other branches after i couldn't proceed because there was a missing folder `module-1`. However, after i switched to the `python` branch, it was smooth sailing thereafter.

Thank you guys for putting together such a wonderful tutorial of how to integrate different AWS services.

**Comment by abaird986** [comment]
Understood and thanks for the feedback @abiodunajibike !  We've re-emphasized to the team that runs the Developer Center to snyc-up with the repository again ASAP.  It should happen soon.

Thanks again for using the tutorial!
