### ISSUE TITLE
Incorrect git command

### ISSUE THREAD

**Issue by HarrisHePeng** [aws-samples/aws-modern-application-workshop#39]
Hello, 
on the webpage https://aws.amazon.com/getting-started/projects/build-modern-app-fargate-lambda-dynamodb-python/module-one/ 
in step2, use "git clone https://github.com/aws-samples/aws-modern-application-workshop.git" cannot download artifact correctly. It seems that "git clone -b python https://github.com/aws-samples/aws-modern-application-workshop.git" does work.

**Comment by SbgMartin** [comment]
Hi,
still an open issue as the website isn't fixed, yet.
Btw, maybe I was reading wrong but my git clone command was this one:
`git clone https://github.com/aws-samples/aws-modern-application-workshop.git -b python --single-branch  `       

Kind regards
Martin

**Comment by Doug-AWS** [comment]
The web site is probably going to be out of date until late this year. Your clone command should work correctly. I'm working on the Go port and should be done by EOM. We'll update the README.md as we get the ports ready for public consumption.

**Comment by victorarshon** [comment]
Hello,
In my case, the recommended git clone command in the  tutorial "Build a Modern Application on AWS (C#)" does not work. 

git clone https://github.com/aws-samples/aws-modern-application-workshop.git

It does not clone module-* folders. Perhaps, it should be changed on :

 git clone -b dotnet https://github.com/aws-samples/aws-modern-application-workshop.git

Regards
Victor

**Comment by Doug-AWS** [comment]
All of the language-specific instructions will be found in a language-specific branch. The main branch will just become a landing page for the language-specific pages, which we are still working on. Stay tuned for details.

**Comment by NorseGaud** [comment]
Victor is right, the https://github.com/aws-samples/aws-modern-application-workshop/tree/go/module-1 readme doesn't include `-b go`

**Comment by NorseGaud** [comment]
It also says to do `cd aws-modern-application-workshop`, and not `cd aws-modern-application-workshop/module-1` 

Subsequent commands fail without going into the module folder. I know these are small things someone should know, but it does delay the speed at which someone can get through the course.
