### ISSUE TITLE
incorrect path for aws CloudFormation api call

### ISSUE THREAD

**Issue by SbgMartin** [aws-samples/aws-modern-application-workshop#47]
Within module 5, Step 3 "Create the streaming stack", Section C "C: Deploy The Stack Using AWS CloudFormation" the bash command contains an additional subfolder /cfn which is not existent.

Instead of using the proposed statement 

`aws cloudformation deploy --template-file /home/ec2-user/environment/MythicalMysfitsStreamingService-Repository/cfn/transformed-streaming.yml --stack-name MythicalMysfitsStreamingStack --capabilities CAPABILITY_IAM`

this one is correct:

`aws cloudformation deploy --template-file /home/ec2-user/environment/MythicalMysfitsStreamingService-Repository/transformed-streaming.yml --stack-name MythicalMysfitsStreamingStack --capabilities CAPABILITY_IAM`

**Comment by abaird986** [comment]
Thanks for raising this @SbgMartin.  I do see that there was an issue where the README text was asking folks to look inside the ./cfn/ directory where the template was copied to. But the `sam package` command actually transformed the template in place and has it created in the same directory that's listed in what you have as the 
>correct statement

It looks like the command you have listed as the "correct statement" is the same one that's listed in the instructions, in case I'm looking in the wrong place.

>Deploy the Stack using AWS CloudFormation

>Also returned by the SAM CLI command is the CloudFormation command needed to be executed to create our new full stack. But because our stack creates IAM resources, you'll need to add one additional parameter to the command. Execute the following command to deploy the streaming stack:

```
aws cloudformation deploy --template-file /home/ec2-user/environment/MythicalMysfitsStreamingService-Repository/transformed-streaming.yml --stack-name MythicalMysfitsStreamingStack --capabilities CAPABILITY_IAM
```

But I did notice that the README was asking folks to look in the /cfn/ folder for the transformed template. So I've submitted a PR to correct that expectation. 

I'll close this issue once you've had a look and let me know if there was something else that I missed. Thanks again!

**Comment by SbgMartin** [comment]
Hi @abaird986 ,
the instructions on the webpage
https://aws.amazon.com/de/getting-started/projects/build-modern-app-fargate-lambda-dynamodb-python/module-five/

have this command:

aws cloudformation deploy --template-file /home/ec2-user/environment/MythicalMysfitsStreamingService-Repository**/cfn/**transformed-streaming.yml --stack-name MythicalMysfitsStreamingStack --capabilities CAPABILITY_IAM

Which did not work for me.

**Comment by abaird986** [comment]
Ah! Understood. That page is unfortunately out of date, and you are not the first person to succumb to errors because of how out-of-date its become.  We're going to have that version of the tutorial updated ASAP, but until then we've added a note to the GitHub repo main README so that folks know its out of date.

If you follow the instructions directly here in the repo instead of on that page, you'll find the most up-to-date version of the workshop.

Apologies again!
