### ISSUE TITLE
in module-1 environment.prod.ts is missing

### ISSUE THREAD

**Issue by flitta** [aws-samples/aws-modern-application-workshop#54]
In order to run `npm run build -- --prod` the file 
`\module-1\frontend\src\environments\environment.prod.ts` is needed. This file will only be added in module-2.
So as a nodejs newby it took me while to figure it out.

I am running the dotnet tutorial on windows 10.

**Comment by allenmichael** [comment]
Great call out! I added specific instructions to the README to create the file in Module 1. We shouldn't add that file explicitly because you generally don't want to check in your `environment.prod.ts` to source control. Thanks for pointing this out!
