### ISSUE TITLE
Unable to detach/delete 2 Network Interfaces

### ISSUE THREAD

**Issue by nickyfoto** [aws-samples/aws-modern-application-workshop#56]
First thank you for this excellent tutorial.

When I do the clean up, I found that I'm not allowed to detach/delete two ENI due to their attachment to public IP address. 

eni-058655ea3334df9f0: You are not allowed to manage 'ela-attach' attachments.
eni-03aababc6088212ab: You are not allowed to manage 'ela-attach' attachments.

```
➜  aws aws ec2 detach-network-interface --force --attachment-id ela-attach-e44a54d4

An error occurred (OperationNotPermitted) when calling the DetachNetworkInterface operation: You are not allowed to manage 'ela-attach' attachments.
➜  aws aws ec2 detach-network-interface --force --attachment-id ela-attach-6d438c50

An error occurred (OperationNotPermitted) when calling the DetachNetworkInterface operation: You are not allowed to manage 'ela-attach' attachments.
```
Therefore all other attach components cannot be deleted. I also found people have similar problem https://forums.aws.amazon.com/thread.jspa?messageID=877939&#877939

Any idea how to remove these ENI ?

**Comment by abaird986** [comment]
Hi @nickyfoto!

Can you determine which resource the ENI is attached to?  It is likely attached to a resource that is managed by another AWS service (like your network load balancer, or Fargate tasks).  For those cases, if you delete/terminate the managed resources themselves, the ENI will also be detached/deleted by the service managing that resource.

Let us know what you find!

**Comment by nickyfoto** [comment]
I managed to delete these after some modification regarding its endpoint services. (I forgot the exact action).

Thank you! I'll close the issue.

**Comment by sankmane** [comment]
> Hi @nickyfoto!
> 
> Can you determine which resource the ENI is attached to? It is likely attached to a resource that is managed by another AWS service (like your network load balancer, or Fargate tasks). For those cases, if you delete/terminate the managed resources themselves, the ENI will also be detached/deleted by the service managing that resource.
> 
> Let us know what you find!

Hi I am facing the same problem and getting the same error my NI is not attached to any service

**Comment by sankmane** [comment]
> > Hi @nickyfoto!
> > Can you determine which resource the ENI is attached to? It is likely attached to a resource that is managed by another AWS service (like your network load balancer, or Fargate tasks). For those cases, if you delete/terminate the managed resources themselves, the ENI will also be detached/deleted by the service managing that resource.
> > Let us know what you find!
> 
> Hi I am facing the same problem and getting the same error my NI is not attached to any service

No nothing is running still ENI is showing in use with description AWS created network interface for directory d-90671f***

**Comment by kenhosr** [comment]
I was able to remove ENI after:
1. VPC Dashboard
2. Endpoint Services
3. find related Endpoint Services
4. `Disassociate Network Load Balancer`, update `Modify endpoint acceptance settings` to Reject

After that, I am able to use CloudFormation to delete the whole stack

**Comment by rsang** [comment]
I'm having the same problem. When I tried to disassociate network load balancer from Endpoint Services, I got the following error:

The following Network Load Balancers still have existing VPC Endpoint connections and cannot be removed: [arn for the ELB that I cannot delete]

Any idea how to proceed from here?

**Comment by rsang** [comment]
I figured it out. Hope this will help other folks in the future. The issue was I deleted API from API Gateway but forgot to delete the VPC link. Open API Gateway again, select VPC Link and delete the link for the app. If you encounter the "Get started" page for API Gateway, just import the sample app and you will have the access to the VPC Link menu option. The following issue explained the same solution: https://github.com/aws-samples/aws-modern-application-workshop/issues/93

**Comment by jangia** [comment]
@rsang Thank you, saved me a lot of time!

**Comment by rahul-satal** [comment]
Just follow the instruction - https://aws.amazon.com/premiumsupport/knowledge-center/vpc-detach-or-delete-eni/

**Comment by davepattie** [comment]
If the endpoint service is a private link you first need to reject the endpoint connections, then you are able to disassociate the existing NLB(s).  Once done you can accept the endpoint connections again.  It should be noted that rejecting the connections does not result in the connection request being removed, it simply sits in the rejected state awaiting approval again which takes a number of minutes to be confirmed from pending

**Comment by resistdesign** [comment]
For anyone finding this that has publish **MULTIPLE** **VERSIONS** of a **LAMBDA**, that could be your issue.
Delete the version of the Lambda (if you no longer need it) that had the network interface associated with it.
Then the network interface is detached and you are able to delete any related subnets as well.

**Comment by parmouraly** [comment]
In my case I had to first manually **delete the associated NAT gateway**.

**Comment by refayathaque** [comment]
What did the trick for me was to delete the associated Load Balancer.

**Comment by Krepenzis** [comment]
My succeeded scenario was deleting associated VPC Endpoint first.

**Comment by hassanejaz** [comment]
For me it was the EFS file system!

**Comment by b1n9s** [comment]
> For anyone finding this that has publish **MULTIPLE** **VERSIONS** of a **LAMBDA**, that could be your issue. Delete the version of the Lambda (if you no longer need it) that had the network interface associated with it. Then the network interface is detached and you are able to delete any related subnets as well.

Same for me. One thing to note is sometimes your Lambda version might not even be showing on the AWS Console due to previous deletions, then you may need to just use the cli to delete the versions: `aws lambda delete-function --function-name my-function:1`
