### ISSUE TITLE
In lab 1 when setting up git secrets you also need to run --register-aws

### ISSUE THREAD

**Issue by C45tr0** [aws-samples/aws-modern-application-workshop#65]
Not only do you need to run `git secrets --install` but you also need to run `git secrets --register-aws`

**Comment by hub714** [comment]
Sorry for not responding earlier...

https://github.com/aws-samples/aws-modern-application-workshop/tree/fargate/workshop-2/Lab-1#build-security-right-into-git-commits

Has both.
