### ISSUE TITLE
Module 2: create-stack error

### ISSUE THREAD

**Issue by Polkendotts** [aws-samples/aws-modern-application-workshop#72]
I am having trouble in Module 2a Step 1, deploying the Templates. 

Following this command:
aws cloudformation create-stack --stack-name MythicalMysfitsCoreStack --capabilities CAPABILITY_NAMED_IAM --template-body file://~/environment/aws-modern-application-workshop/module-2/cfn/core.yml

My stack fails to create. Looking into the details on my Cloud Formation Console, the first error is as follows:

MythicalMysfitsServiceCodeBuildServiceRole already exists

Then it triggers a rollback of the entire stack. I've tried deleting the stack and attempting to create it again, always with the same issue. I suspect I am not fully deleting it from the cloud. However, this does not explain the initial failure.

**Comment by Doug-AWS** [comment]
Try deleting the role manually:

aws iam delete-role --role-name Test-Role

Note that (according to https://docs.aws.amazon.com/cli/latest/reference/iam/delete-role.html):

Before you can delete a role, you must remove the role from any instance profile (remove-role-from-instance-profile), detach any managed policies (detach-role-policy) and delete any inline policies that are attached to the role (delete-role-policy).

**Comment by abaird986** [comment]
@Polkendotts - let us know if this issue still persists for you. Closing now!

**Comment by RedaBenlakehal** [comment]
hello @abaird986  this issue still persists for me !!
