### ISSUE TITLE
Module 3 and Module 4 Go Code is inconsistent and doesn't work.

### ISSUE THREAD

**Issue by borkod** [aws-samples/aws-modern-application-workshop#74]
Module 3 has a separate client folder with the Go client code for accessing Dynamo DB.  The instructions only contain directions to copy services folder:

cp ~/environment/aws-modern-application-workshop/module-3/app/service/* ~/environment/MythicalMysfitsService-Repository/service/

This results in a non-working solution.  The Docker build will fail.

In Module 4, the folder structure of Go code is different.  "mysfitsTableClient.go" file is now in the service folder.  The code pipeline seems to build fine, but the API doesn't seem to work.

**Comment by Doug-AWS** [comment]
I'm on it.

**Comment by Doug-AWS** [comment]
I fixed this on Jan 7. See https://github.com/aws-samples/aws-modern-application-workshop/commit/61f9f64899b2f7ded439453ec1fe42ec573736af#diff-fdbdb0bfd504e7fbadba4d2fb7f2e093.

**Comment by ckygel** [comment]
@borkod is right, just following the instructions causes build process to fail. I had to delete Dockerfile from Mythical repo, and copy paste Dockerfile from module-3 folder to repo for build to pass.
