### ISSUE TITLE
Unable to detach/delete 2 Network Interfaces #56

### ISSUE THREAD

**Issue by dbw12345** [aws-samples/aws-modern-application-workshop#76]
Really appreciated this project. Thanks to AWS. But having issues with clean up.

I am having the same issue raised in #56. As recommended by @abaird986, I deleted ECS resources (i.e. Fargate) but still cannot delete NLB or VPC. When trying to delete mysfits-nlb, I get error:

Load balancer 'arn:aws:elasticloadbalancing:us-east-1:641860735165:loadbalancer/net/mysfits-nlb/82ff6e1df96b980a' cannot be deleted because it is currently associated with another service.

When trying to delete the VPC, I get error:

Unable to delete this VPC:
The VPC contains one or more in-use network interfaces, and cannot be deleted until those network interfaces have been deleted. 
View in-use network interfaces in the VPC.
eni-098d350b165da699f
eni-09e539d8f129d5008

When trying to detach a network interface, I get error:

Error deleting network interface
eni-098d350b165da699f: You are not allowed to manage 'ela-attach' attachments.

Thanks in advance.

**Comment by ramnarayanp** [comment]
i too was having the same problem a little earlier today, but i was able to clean it all up. It was really cumbersome, but i got it done finally. I think, the steps i followed was to go to the service end points and deleted them manually before attempting the n/w interface clean up. can you please try that?

**Comment by dbw12345** [comment]
Thanks, @ramnarayanp.

I have worked through the clean up again and found some additional resources such as:

*Deletion of CloudWatch logs.
*Deletion of Listener associated with nlb,
*Deletion of Target Groups.
*Rejection of endpoint in Endpoint Services/Endpoint Connections.

This enabled deletion of the network load balancer.

I then deleted the subnets, and a few other resources. To be honest, I have lost track of the exact things I have done because there were so many resources hidden under layers!

Anyway, I have been able to delete the CoreStack. Thanks for the response and advice.

**Comment by ramnarayanp** [comment]
The creators of this project could it better  with documenting the clean up!

**Comment by dbw12345** [comment]
It definitely can be improved, but to document it properly, they'd have to add a sixth module! There are so many resources created throughout the project. As a beginner, it is hard to comprehend all the things that are being created.

**Comment by passionatedevops** [comment]
**Solution**
Look at the "Description" column of "Network Interfaces" (which is under "Network and Security").  Find the relevant item, device or object (e.g., if you see ELB go to Load Balancing -> Load Balancers, if you can see FS > go to EFS etc).  Delete this object . Then go back and delete the Network Interface.  Now you can delete the Security Group

**Comment by pavankumarupadhyayula** [comment]
Please Delete all CloudWatch Logs and Verify.

**Comment by th3r10n** [comment]
@passionatedevops ,
How come deleting the ELB is the solution when in fact the problem is not being to delete the ELB?

**Comment by th3r10n** [comment]
I deleted the cluster, service, target groups, listener, log groups and still was not able to delete the ELB.
After that:
1) Go to API Gateway --> APIs and delete the Mysfits REST API.
2) Go to API Gateway --> VPC links and delete the VPC link created for that API. 
After that I was able to delete the mysfits-nlb.
AWS should definitely add a sixth module just for the clean up.

**Comment by andypuckett** [comment]
Delete the Endpoint Service
