### ISSUE TITLE
In module 2 of Go - CORS is not set up

### ISSUE THREAD

**Issue by donis** [aws-samples/aws-modern-application-workshop#78]
After finishing 2a part - my mysfits were not showing up :( Reason being - API was not returning proper CORS headers (they are only set up later in API Gateway).

I was able to solve it by adding https://github.com/rs/cors as a middleware and using default configuration, would it be fine to create a PR with this addition?

**Comment by Doug-AWS** [comment]
We should be able to copy the setupResponse function from module-4/app/service/mythicalMysfitsService.go and then call it at the top of every handler. I'll do that tomorrow morning.

**Comment by Doug-AWS** [comment]
Never mind. It was an easy fix, so I did it. I also replaced all of the tabs in the Go source files with 4 spaces.

**Comment by donis** [comment]
Awesome, thanks!
