### ISSUE TITLE
Directions say there should be a cfn directory

### ISSUE THREAD

**Issue by maverick976** [aws-samples/aws-modern-application-workshop#85]
> If successful, you will see the newly created transformed-streaming.yml file exist within the ./cfn/ directory, if you look in its contents, you'll see that the sourceUri parameter of the serverless Lambda function has been updated with the object location where the SAM CLI has uploaded your packaged 
> 

There is no cfn directory. the file is in the root of the project. You have to create a cfn directory and move the file there. The command to create the new s3 buckets seems to be missing in the prior step as well.

**Comment by abaird986** [comment]
Hey @maverick976  - which branch of the repository were you using to follow the workshop instructions?

**Comment by maverick976** [comment]
I was following the steps posted on the AWS website

**Comment by abaird986** [comment]
Thanks for the detail and for pointing this out! The team that maintains the AWS website version of the tutorial has been informed of the discrepancy. It will be updated soon.  

Will close this issue when I can confirm the change has been pushed.

**Comment by abaird986** [comment]
This correction has been pushed to the aforementioned AWS website.  Thanks for identifying it and raising the issue!
