### ISSUE TITLE
Feedback on workshop-1, lab 4

### ISSUE THREAD

**Issue by tfcaod** [aws-samples/aws-modern-application-workshop#87]
The instruction link below mentioned "Find the app/monolith-service/service/mythicalMysfitsService.py source file, and **uncomment the following section**"

https://github.com/aws-samples/aws-modern-application-workshop/tree/fargate/workshop-1#instructions-2

Feedback: Need to remind user to remove extra whitespace when removing "#" to avoid indentation error.

**Comment by abaird986** [comment]
The module related to this issue has moved to:
https://github.com/aws-samples/amazon-ecs-mythicalmysfits-workshop 

Thanks!
