### ISSUE TITLE
Failed to launch task error

### ISSUE THREAD

**Issue by emcginty70** [aws-samples/aws-modern-application-workshop#88]
I'm getting the following error message in ECR console, I removed the 

service MythicalMysfits-Service failed to launch a task with (error ECS was unable to assume the role 'arn:aws:iam::281174624655:role/MythicalMysfitsCoreStack-ECSTaskRole-FXO3A6J08BN' that was provided for this task. Please verify that the role being passed has the proper trust relationship and permissions and that your IAM user has permissions to pass this role.).

I've quadruple checked the task-definitions json file and IAM.  The look correct.

**Comment by abaird986** [comment]
Hey @emcginty70 - be sure that you've got the right roles placed, there are two ECS roles (one for tasks and one for the service).  Could you quintuple check that those roles aren't flipped?

**Comment by abaird986** [comment]
Gonna close this issue, please don't hesitate to open it again if you're still hitting the issue. Would be great if you can share the error message as well as the json artifacts used when creating the service so we can help debug.

**Comment by Bharathkumarraju** [comment]
Any resolution for this?

**Comment by chasingmonkeys** [comment]
Hello,

When trying to run: 
aws ecs create-service --cli-input-json file://~/environment/aws-modern-application-workshop/module-2/aws-cli/service-definition.json

I get the following event log; 

service MythicalMysfits-Service failed to launch a task with (error ECS was unable to assume the role 'arn:aws:iam::xxx:role/xxx' that was provided for this task. Please verify that the role being passed has the proper trust relationship and permissions and that your IAM user has permissions to pass this role.).

Any help would be much appreciated.

**Comment by quantheads** [comment]
hi - any resolution here?

**Comment by aimtyaem** [comment]
Can you give me few outlines?

Ahmed Metawee
Freelance Consultant
#aimty @aimty

________________________________
