### ISSUE TITLE
Invalid principal in policy

### ISSUE THREAD

**Issue by prathusha94** [aws-samples/aws-modern-application-workshop#89]
Trying to update the s3 bucket policy by following the instructions in section B.
Replaced the string "REPLACE_ME_BUCKET_NAME" with the name of the bucket i have created in the following command.
`aws s3api put-bucket-policy --bucket REPLACE_ME_BUCKET_NAME --policy file://~/environment/aws-modern-application-workshop/module-1/aws-cli/website-bucket-policy.json
`
And this is the error I get : `An error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Invalid principal in policy`

This is the JSON file 

`{
    "Version": "2008-10-17",
    "Id": "PolicyForCloudFrontPrivateContent",
    "Statement": [
        {
            "Sid": "1",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity REPLACE_ME_CLOUDFRONT_ORIGIN_ACCESS_IDENTITY_ID"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::mythicalbucket1"
        }
    ]
}`

I tried reading the documentation for "Principle" and gave the "*" value since we are trying to grant public access but that gives error too.

This is the first time I'm working with AWS so would appreciate if anyone can help me with this.

**Comment by prathusha94** [comment]
The files provided in this repository use Amazon CloudFront for which the instructions are not explicitly mentioned. 
 If you do not want to use CouldFront , replace the value for Principal as
`"Principal": "*"

`
Also make sure that for Resource, there is a"/* after the bucket name. (this was the mistake I was doing"

**Comment by dsclambton** [comment]
I run into the same problem. My bucket policy is the exactly same as the one in the AWS doc, but it says principal is invalid.
```
                {
            "Effect": "Allow",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::flybits-pci-file-manager/*",
            "Principal": {
		        "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity <MY-OAI-ID>"
		        }
        }
```

I'm wondering what's the way out of this issue.
