### ISSUE TITLE
ECS ROLE ARN

### ISSUE THREAD

**Issue by jschwarzwalder** [aws-samples/aws-modern-application-workshop#9]
```
  "executionRoleArn": "REPLACE_ME_ECS_ROLE_ARN",
  "taskRoleArn": "REPLACE_ME_ECS_TASK_ROLE_ARN",
```
I'm not certain which value to place in these. I have an arn for cloud formation and only one from ecs that I got when I created the cluster.  What goes where?

"repositoryArn": "arn:aws:ecr:"
"StackId": "arn:aws:cloudformation:"
"Arn": "arn:aws:iam:"
"clusterArn": "arn:aws:ecs:"

Is there a command I can run at this point to retrieve in information in case I forgot to save the file?

Thank you for clarifying

**Comment by jschwarzwalder** [comment]
I tried using the ecs for "executionRoleArn" that I got from create-cluster command, and the cloud formation arn for "taskRoleArn" but got the following error:

```
An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Role is not valid
```

**Comment by rttomlinson** [comment]
If you go to "CloudFormation" in the AWS console and locate the stack you made originally, you should find an "Outputs" tab. In there you will find the ARNs for ECS role and ECS Task role.

**Comment by abaird986** [comment]
@jschwarzwalder - look at this bit within the instructions of module 2, the describe-stacks call is the one that was missed that contains lots of the values you'll need to copy and paste later in the workshop:

You can check on the status of your stack creation either via the AWS Console or by running the command:

'aws cloudformation describe-stacks --stack-name MythicalMysfitsCoreStack'

When in the describe-stacks response, you see a status of CREATE_COMPLETE, CloudFormation has finished provisioning all of the core networking and security resources described above.

Once you see CREATE_COMPLETE in the describe-stacks response command above, copy the full response and save it for future reference in a text editor. Or, create a temporary folder and file to save it to within your IDE. This JSON response contains the unique identifiers for several of the created resources, which we will use later in this workshop.

**Comment by jschwarzwalder** [comment]
I recovered from error by running  this to get the information I needed. 

`aws cloudformation describe-stacks --stack-name MythicalMysfitsCoreStack` 

The paragraphs are very dense, and so it was hard to understand that I would need to wait until I get a different status.

**Comment by samuelj123** [comment]
I get 
`An error occured (ClientException) when calling the RegisterTaskDefinition operation: Role is not valid`
when I run
`aws ecs register-task-definition --cli-input-json file://taskdef.json`
Should I be playing around with my IAM roles? if so, which?

**Comment by andreayully** [comment]
I have the error 
`An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Role is not valid`
in the information i get from `aws cloudformation describe-stacks --stack-name MythicalMysfitsCoreStack` i did not get the executionRoleArn

**Comment by shrihari21** [comment]
> I get
> `An error occured (ClientException) when calling the RegisterTaskDefinition operation: Role is not valid`
> when I run
> `aws ecs register-task-definition --cli-input-json file://taskdef.json`
> Should I be playing around with my IAM roles? if so, which?

Me to facing same isssue , do u have any solution ?

**Comment by karthikeayan** [comment]
1. Make sure the role is in the same account where you are trying to execute runTask
2. Make sure the role has ecs-tasks trust relationship
3. Make sure the role has required permissions
