### ISSUE TITLE
module 6 typo

### ISSUE THREAD

**Issue by bushki** [aws-samples/aws-modern-application-workshop#90]
In Module 6 the instructions for uncommenting do no match the code.
The python code is missing one "M" in "comment"

**Instructions** 
UNCOMMENT_BEFORE_3RD_DEPLOYMENT

**Code** 
UNCOMENT_BEFORE_3RD_DEPLOYMENT

**Comment by abaird986** [comment]
Thanks for catching, just merged in the correction. Feel free to submit a PR for something like this if you'd like to in the future!
