### ISSUE TITLE
Module 2: CodeBuild fails

### ISSUE THREAD

**Issue by ekrasikov** [aws-samples/aws-modern-application-workshop#95]
Please see log below.

Adding permissions  "ecr:UploadLayerPart" and "ecr:CompleteLayerUpload" to MythicalMysfitsService-CodeBuildServicePolicy helps.

denied: User: arn:aws:sts::<CUT>:assumed-role/MythicalMysfitsServiceCodeBuildServiceRole/AWSCodeBuild-4c4a1c09-bbca-4853-9d15-e18fe7c6f667 is not authorized to perform: ecr:CompleteLayerUpload on resource: arn:aws:ecr:eu-west-1:026927173535:repository/mythicalmysfits/service
 [Container] 2019/04/03 07:22:13 Command did not exit successfully docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mythicalmysfits/service:latest exit status 1
[Container] 2019/04/03 07:22:13 Phase complete: POST_BUILD State: FAILED

**Comment by xojixho** [comment]
what was the problem ? 
I have the same issue
