### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by mnahme18** [aws-samples/aws-modern-application-workshop#98]
I have been getting this error when creating the policy for the S3.
I have tried many things like changing the ID name in different ways and changing the bucket name. 

error occurred (MalformedPolicy) when calling the PutBucketPolicy operation: Invalid principal in policy

**Comment by abaird986** [comment]
Hmm, there are lots of different possibilities here. It's important the you've got the bucket name filled in appropriately and the CloudFront Origin Access ID (if you're using the Python branch) inserted appropriately.

Check out these docs pages for some examples:
https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html#example-bucket-policies-use-case-6

If you could, could you paste here the policy you're using that's leading to an error? You can obfuscate the bucket name and Cloudfront Origin Access Id when sharing to keep your specifics private.

**Comment by mnahme18** [comment]
I am using python. 


{
    "Version": "2008-10-17",
    "Id": "PolicyForCloudFrontPrivateContent",
    "Statement": [
        {
            "Sid": "1",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::cloudfront:user/ID_NUMBER"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::BUCKET_NAME/*"
        }
    ]
}

**Comment by Doug-AWS** [comment]
Take a look at the example in our code catalog: https://docs.aws.amazon.com/code-samples/latest/catalog/python-s3-s3-python-example-put-bucket-policy.py.html

**Comment by abaird986** [comment]
@mnahme18  - you will actually include the words "CloudFront Origin Access Identity" in the policy, ahead of your specific access identity ID, it'll look like below:

"AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity XXXXXXXXXXX

**Comment by abaird986** [comment]
Hoping the above suggestion provided assistance required, going to close this out now.
