### ISSUE TITLE
Unable to assume the service linked role upon service creation

### ISSUE THREAD

**Issue by chughes87** [aws-samples/aws-modern-application-workshop#99]
I'm not sure if there was an error on my part, but when I got to this section: https://github.com/aws-samples/aws-modern-application-workshop/tree/go/module-2#create-the-service and tried to run the command there (`aws ecs create-service --cli-input-json file://~/environment/aws-modern-application-workshop/module-2/aws-cli/service-definition.json`), I was getting the following error message: `An error occurred (InvalidParameterException) when calling the CreateService operation: Unable to assume the service linked role. Please verify that the ECS service linked role exists.`. I was able to get past this issue after reading through https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html and running `aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com` in the console to create the missing role.

The linked docs state, "Under most circumstances, you don't need to manually create a service-linked role." So I'm imagining there is some issues with my permissions or something. But the error message didn't say anything about that?

**Comment by abaird986** [comment]
Ah, thanks for pointing this out, it's been addressed in the Python branch, but not yet the Go branch. See here:
https://github.com/aws-samples/aws-modern-application-workshop/tree/python/module-2

I'll add it to my list for next week to add these instructions to the other language branches as well. If someone would like to submit a PR themselves for it ahead of then, feel free!

I'll leave this open until the updates are merged into each language branch.

**Comment by davidrwillson** [comment]
Thanks for the fix.  Just ran into the same problem.  BTW - thank you for this workshop.  It is great!

**Comment by abaird986** [comment]
Finally resolved this :)
